### ISSUE TITLE
Group instance

### ISSUE THREAD

**Issue by matthewleon** [hdgarrood/purescript-modular-arithmetic#1]
Thoughts?

**Comment by hdgarrood** [comment]
I'm not hugely keen, because we'd have to give `Z` a `Monoid` instance using addition. Of course for `Int` we avoid doing that because there are two equally good choices; this is why we have `Additive` and `Multiplicative`.

**Comment by matthewleon** [comment]
Ah, right, there is a `Ring` instance, so we can just choose the `Additive` monoid as needed.
