### ISSUE TITLE
thoughts on integration with purescript-sized-vectors

### ISSUE THREAD

**Issue by matthewleon** [hdgarrood/purescript-modular-arithmetic#3]
Treating value-level indexes on `purescript-sized-vectors` arrays as ℤ/nℤ would allow for a number of nice tricks. Thoughts?

**Comment by hdgarrood** [comment]
What sort of tricks? I'm tempted to say that kind of thing is outside the scope of this library. Or are you suggesting changes to sized-vectors?

**Comment by matthewleon** [comment]
I think actually the changes would go on sized-vectors, yes.

The tricks would involve using these for all kinds of operations involving indexes, including `find`, etc.

**Comment by hdgarrood** [comment]
Seems worth exploring, sure, although I'm probably not going to do so personally. Do you mind if I close this then?
